info:
  name: "@project.artifactId@"
  version: "@project.version@"
  description: "@project.description@"
  running-profile: "${spring.profiles.active}"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname:  localhost
    instance-id: ${spring.application.name}:${random.int}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/farms?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: SaAm_4106
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 1002