info:
  name: "@project.artifactId@"
  version: "@project.version@"
  description: "@project.description@"
  running-profile: "${spring.profiles.active}"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka
    register-with-eureka: false
    fetch-registry: false
  environment: Local
  datacenter: Buenos Aires

server:
  port: 1001