info:
  name: "@project.artifactId@"
  version: "@project.version@"
  description: "@project.description@"
  running-profile: "${spring.profiles.active}"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname:  localhost
    instance-id: ${spring.application.name}:${random.int}

server:
  port: 1005